$(document).on("click", "#somebutton", function() {
			var x= $('#somebutton')										// When HTML DOM "click" event is invoked on element with ID "somebutton", execute the following function...
    $.get("Search", function(responseText) {   // Execute Ajax GET request on URL of "someservlet" and execute the following function with Ajax response text...
        $("#somediv").text(responseText);           // Locate HTML DOM element with ID "somediv" and set its text content with the response text.
    });
});
